GET http://localhost:3000/events

###
@eventID = be6dc6af-f553-4a5e-a869-ac1cbf957a6a


###
GET http://localhost:3000/events/{{eventID}}/spots
###
# @name createSpot
POST http://localhost:3000/events/{{eventID}}/spots
Content-Type: application/json

{
  "name": "new Spot"
}
###

@spotID = {{ createSpot.response.body.id }}



###
GET http://localhost:3000/events/{{eventID}}/spots/{{spotID}}

###
PATCH  http://localhost:3000/events/{{eventID}}/spots/{{spotID}}
Content-Type: application/json

{
  "name": "New Event Update"
}



###
DELETE http://localhost:3000/events/{{eventID}}/spots/{{spotID}}


